[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=/NODEFAULTLIB /DEF:windows.def"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=rust-lld", "-L", "glibc-x64"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "linker=rust-lld", "-L", "glibc-aarch64"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "linker=rust-lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "linker=rust-lld"]
